title: bigQM7w
logo: JustBODIPY.svg
description: A high-quality dataset of ground-state properties and excited state spectra of 12880 molecules containing up to 7 atoms of CONF
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
defaults:
layout: single
